### ISSUE TITLE
Using own distance matrix for clonotype_network

### ISSUE THREAD

**Issue by andreas-wilm** [scverse/scirpy#286]
Hi there,

thanks again for making this wonderful tool publicly available. I would like to know if it's possible to use my own clonotypes and clonotype distance matrix as input for the clonotype network routines? If yes, what are the required steps and which steps in [the tutorial](https://icbi-lab.github.io/scirpy/develop/tutorials/tutorial_3k_tcr.html#Compute-CDR3-neighborhood-graph-and-define-clonotypes) should be skipped? Some more background: In my case I would like to use the distance output matrix from [TCRdist3](https://tcrdist3.readthedocs.io/en/latest/) and the "clonotype" definition I used as its input.

Many thanks, Andreas

**Comment by grst** [comment]
Hi Andreas, 

this is an excellent question and the answer depends:

Using custom **clonotypes** is easy: you can just add them as column to `adata.obs`. 

Providing distances between **sequences** is still rather straightforward. This replaces the call to `pp.ir_dist`. 
 * You could just add a dictionary with sparse distance matrix to `adata.uns["ir_dist_{key}"]` for VJ and VDJ sequences separately. 
 * Or, you could build your own [`DistanceCalculator` class](https://github.com/icbi-lab/scirpy/blob/master/scirpy/ir_dist/metrics.py#L42) and provide it to `pp.ir_dist`. Scirpy then uses this information to `define_clonotypes` based on your settings for  `dual_ir` etc. 

However, I assume that TCRdist3 already provides distances between **cells**. This is a bit trickier, as since version 0.7, scirpy never computes distances between cells, but between unique cells with the same receptor configuration (many cells with the same receptor led to blocks in the sparse distance matrix which was too inefficient for large datasets). This would replace both the call to `pp.ir_dist` and `tl.define_clonotypes` and would essentially require you to replace the dictionary stored in `adata.uns["{clonotype_key}"]`. It has the following structure: 

 * `distances`: sparse pairwise distance matrix between all *unique cells*. 
 * `cell_indices`: dictionary of lists. Each numeric index of the distance matrix points to a numpy array of indices (i.e. adata.obs_names) of cells with the same receptor configuration. Dictionary keys need to be strings despite being numeric because of reasons (looking at you, h5py :roll_eyes:)

That being said, I believe it could even work to just provide a cell x cell matrix and use a 1:1 mapping for `cell_indices`, like

```python
adata.uns["{clonotype_key}"] = {
   'distances' : YOUR_MATRIX,
   'cell_indices': { str(i): np.array([cell]) for cell in adata.obs_names } 
}
```

if you can afford the additional memory consumption. Also, this wouldn't "summarize" indentical cells to a single node any more. 

In any case, keep me posted how this works out. It could even be interesting to add support for the tcrdist package directly to scirpy (for instance `ir.external.tcrdist3()`)

Cheers, 
Gregor

**Comment by zktuong** [comment]
I'm also interested in this. A simple usage of scirpy's plotting code is failing for me when i just put in a pre-computed distance matrix from dandelion in that edges were connecting between two clones. Maybe it's an indexing problem. I'll do a bit of further testing and show an example soon.

**Comment by andreas-wilm** [comment]
Hi Gregor, apologies it took me some time to get back to this. TCRdist3 computes distances between precompiled, user-defined clonotypes / groups of cells with the identical TCR composition, where the exact definition is up to the user.  So I guess `pp.ir_dist` and `tl.define_clonotypes` become redundant and I could try to create `adata.uns["{clonotype_key}"]` directly. I'm unclear how this is structured though. Does each row in `distances` map to a `cell_indices` key? Could you by any chance provide a minimal example? Many thanks

**Comment by grst** [comment]
Here's an example: 

```python
import scirpy as ir
import pandas as pd
import scanpy as sc
import scipy.sparse as sp
import numpy as np

# setup anndata with 4 fake cells and three clonotypes (c0, c1, c2)
# c1 is connected to c2, c0 is disconnected from c1 and c2
adata = sc.AnnData(
    obs=pd.DataFrame()
    .assign(
        cells=["cell1", "cell2", "cell3", "cell4"], clone_id=["c0", "c0", "c1", "c2"]
    )
    .set_index("cells")
)

adata.uns["clone_id"] = {
    # this is a symmetrical, pairwise, sparse distance matrix of clonotypes
    # the matrix is offset by 1, i.e. 0 = no connection, 1 = distance 0
    "distances": sp.csr_matrix([[1, 0, 0], [0, 1, 1], [0, 1, 1]]),
    # '0' refers to the row/col index in the `distances` matrix (numeric index, but needs to be str because of h5py)
    # np.array(["cell1", "cell2"]) points to the rows in `adata.obs`
    "cell_indices": {
        "0": np.array(["cell1", "cell2"]),
        "1": np.array(["cell3"]),
        "2": np.array(["cell4"]),
    },
}

ir.tl.clonotype_network(adata)
ir.pl.clonotype_network(adata, base_size=50)
```

![image](https://user-images.githubusercontent.com/7051479/135422282-8d15c329-f5ed-4642-8f5a-6902f4d40929.png)

**Comment by grst** [comment]
Internally, distances are converted to some sort of connectivities anyway:
https://github.com/icbi-lab/scirpy/blob/113ee731bf39c508a6cf049fd87e27fb93685811/scirpy/util/graph/__init__.py#L51-L84

However, it is currently not supported to specify `'connectivities` directly in `adata.uns["clone_id"]`. Could you elaborate on your use-case?

**Comment by andreas-wilm** [comment]
Apologies. I just came across this open issue again which I had left orphaned. Sorry again. I don't remember all the details, but at least for my ["weird plot" issue](https://github.com/icbi-lab/scirpy/issues/286#issuecomment-945556652) it turned out that this was an issue on my side. It was related to how I used TCRdist3 `TCRrep.clone_df` and `cell_df` (they don't necessarily have the same order, even if you turned cell_df into a clonotype df). See https://github.com/kmayerb/tcrdist3/issues/60 for more info. Anyway, not a Scirpy issue at all. I've moved on to other visualizations since, but am pretty sure this can be closed

**Comment by grst** [comment]
Closing this for now - LMK if there are any other questions!

**Comment by andreas-wilm** [comment]
Sorry Gregor. I just got the closing notification and realized I had missed one of your questions:

> One final question: I would be curious to learn why you chose TCRdist3 over scirpy's ir_dist? As far as I understand the TCRdist3 docs, they work quite similar.

Plain and simply speed. We have access to 10s of thousands of clonotypes and the comparison gets very slow in that case.
