### ISSUE TITLE
"read_10x_vdj" not loading data properly

### ISSUE THREAD

**Issue by mwetzel7** [scverse/scirpy#503]
**Describe the bug**
When trying to load VDJ data into environment with the "read_10x_vdj" function, it only loads the barcodes and none of the other information in the csv file. When checking the adata.obs I only see "cell_id" with barcodes and nothing else.

**To Reproduce**
adata = ir.io.read_10x_vdj("path/to/filtered_contig_annotations.csv")

**Expected behaviour**
When I check adata.obs I expected to see associated data pulled from the csv file.

**System**
-   OS: MacOS Sonoma 14.4
-   Python version: 3.11.8 (also tried 3.9.19)
-   Versions of libraries involved: scanpy==1.9.7 anndata==0.10.6 umap==0.5.6 numpy==1.26.4 scipy==1.13.0 pandas==2.2.1 scikit-learn==1.4.1.post1 statsmodels==0.14.1 igraph==0.11.4 pynndescent==0.5.12 scirpy==0.16.0 (also tried scirpy==0.13.1)

**Additional context**
I get no explicit errors when I try to run the "read_10x_vdj" function but I do get this warning: "ExperimentalFeatureWarning: Support for Awkward Arrays is currently experimental". 
The csv files seem to be correct and fully populated. I downloaded the example files used in the tutorial to test and they return the same empty .obs as my files do.
I have tried changing python and scirpy versions and nothing has been working so far.

Thanks for your help!

**Comment by grst** [comment]
Hi @mwetzel7, 

since [scirpy v0.13](https://scirpy.scverse.org/en/latest/changelog.html#v0-13-0-new-data-structure-based-on-awkward-arrays), the receptor data is not stored in `.obs` anymore, but in an awkward array in `.obsm["airr"]`. 

You can learn more about the new data structure here: https://scirpy.scverse.org/en/latest/data-structure.html#storing-airr-rearrangement-data-in-anndata

So likely everything is behaving as expected, if not, let me know!

**Comment by grst** [comment]
Since I don't think there's an actual bug, I am closing this for now. Feel free to reopen if there are any other issues!
